steps:
  # Build and deploy to container registry along with layer cache using kaniko
  - name: "gcr.io/kaniko-project/executor:latest"
    args: ["--destination=gcr.io/$PROJECT_ID/image", "--cache=true", "--cache-ttl=24h"]

  # Deploy to Cloud Run using gcloud CLI
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ["run", "deploy", "gnosis-next", "--image", "gcr.io/$PROJECT_ID/image", "--region", "us-central1", "--platform", "managed", "--allow-unauthenticated"]   
  
  
timeout: 1800s