# steps:
#   # Build from local Docker file using Cloud Builder
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ["build", "-t", "gcr.io/$PROJECT_ID/next", "."]
#   # Push image to Google Container Registry
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ["push", "gcr.io/$PROJECT_ID/next"]
#   # Deploy pushed image to Cloud Run using gcloud cli
#   - name: 'gcr.io/cloud-builders/gcloud'
#     args: ["run", "deploy", "gnosis-next", "--image", "gcr.io/$PROJECT_ID/next", "--region", "us-central1", "--platform", "managed", "--allow-unauthenticated"]    
# timeout: 1800s


steps:
  # Build and deploy to container registry along with layer cache using kaniko
  - name: "gcr.io/kaniko-project/executor:latest"
    args: ["--destination=gcr.io/$PROJECT_ID/image", "--cache=true", "--cache-ttl=24h"]

  # Deploy to Cloud Run using gcloud CLI
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ["run", "deploy", "gnosis-next", "--image", "gcr.io/$PROJECT_ID/image", "--region", "us-central1", "--platform", "managed", "--allow-unauthenticated"]   
  
  
timeout: 1800s